refactor binary caching and improve flash support

diff --git a/.github/workflows/test.composite-action.yml b/.github/workflows/test.composite-action.yml
--- a/.github/workflows/test.composite-action.yml
+++ b/.github/workflows/test.composite-action.yml
@@ -15,6 +15,7 @@ on:
     - '**/*.adoc'
     - '**/*.md'
     - '.github/*.yml'
+    - '.github/workflows/*reusable*.yml'
   pull_request:
   workflow_dispatch:
     # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
@@ -44,11 +45,15 @@ jobs:
     - name: "Test with Haxe"
       uses: ./.github/actions/test-with-haxe
       with:
+        haxe-reusable-workflows-repo:    ${{ github.repository }}
+        haxe-reusable-workflows-version: ${{ github.ref }}
+
         haxe-version: ${{ matrix.haxe }}
         haxe-libs: hx3compat hscript@2.5.0
         test-cpp: true
         test-cs: true
         test-eval: true
+        test-flash: ${{ !startsWith(matrix.os, 'macos') && 'tests-flash.hxml' || false }} # FlashPlayer hangs on MacOS
         test-hl: ${{ matrix.haxe != '3.4.7' }}
         test-java: true
         test-jvm: true
@@ -57,3 +62,14 @@ jobs:
         test-node: true
         test-php: true
         test-python: true
+
+        before-tests: |
+          echo "Preparing tests..."
+  
+        after-tests: |
+          case "$GITHUB_JOB_STATUS" in
+            success)   echo "Job success" ;;
+            failure)   echo "Job failure" ;;
+            cancelled) echo "Job cancelled." ;;
+            *)         echo "ERROR: Unexpected job status $GITHUB_JOB_STATUS"; exit 1 ;;
+          esac
